# Generated by Django 4.2.7 on 2023-11-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('jours_de_travail', models.CharField(max_length=255)),
                ('demi_jour_mercredi', models.BooleanField()),
                ('nombre_jours_de_travail', models.PositiveIntegerField()),
            ],
        ),
    ]
